### ISSUE TITLE
建议增加全局变量

### ISSUE THREAD

**Issue by chaoedu** [debugtalk/ApiTestEngine#3]
登录过程中获取的token，可以在之后的testcase中使用

**Comment by debugtalk** [comment]
这个功能是已经有了的。例如下面的形式，通过`extract_binds`将token提取出来并保存到`user_token`，然后后续的请求都可以直接用了。

```yaml
- test:
    name: login with email to get user token
    request:
        url: /apis/apprest/v1/email_login
        method: POST
        headers:
            Content-Type: application/x-www-form-urlencoded
        data:
            email: $user_email
            password: $user_passwd
    extract_binds:
        user_token: content.data.token
    validators:
        - {"check": "status_code", "expected": 200}
        - {"check": "headers.content-type", "expected": "application/json;charset=UTF-8"}
        - {"check": "content.code", "expected": 0}
        - {"check": "content.message", "expected": "ok"}

- test:
    name: /api/users/user_id/home
    request:
        url: /api/users/$user_id/home
        params:
            page: 1
            page_size: 21
            token: $user_token
        method: GET
    validators:
        - {"check": "status_code", "expected": 200}
        - {"check": "headers.content-type", "expected": "application/json; charset=utf-8"}
        - {"check": "content.status", "expected": 0}
        - {"check": "content.status_msg", "expected": "ok"}
        - {"check": "content.items", "expected": 10, "comparator": "len_gt"}
```
