### ISSUE TITLE
在接口的响应结果确认中，是否也支持变量值的引用

### ISSUE THREAD

**Issue by TyouSF** [debugtalk/ApiTestEngine#43]
# 测试 case 示例

```yaml
- test:
    name: 'test'
    request:
        url: /test
        method: POST
        json:
            device: $device
            version: $version
            testid: $testid
    validators:
        - {'check':'content.checkid', 'comparator':'eq', 'expected':$checkid}
```
其中`$checkid` 是之前绑定的变量或者其他接口响应内容提取绑定的变量的引用

# 问题

这样的写法似乎测试用例无法执行通过，当前是否支持这样在确认结果中对变量的引用？

如果支持，想请问一下写法。。。。
