### ISSUE TITLE
如何在测试用例中，编写类似 setup 和 teardown 的实现

### ISSUE THREAD

**Issue by TyouSF** [debugtalk/ApiTestEngine#45]
# 场景描述：
编写测试用例时，有时需要一些如下操作：
- 测试前，先对测试数据进行一些检验
- 测试后，需要对测试过程中创建的一些内容进行销毁

# 问题：
当前在测试用例的模板中没有看到类似此类型的用例示例，如果需要实现，该如何编写用例？

**Comment by debugtalk** [comment]
@TyouSF 

当前框架已经支持`setup`和`teardown`，但需结合`debugtalk.py`热加载机制实现；

具体地，可将测试前后需要做的工作封装在函数中，放置在`debugtalk.py`中，然后在测试用例中，在`setup`和`teardown`模块中调用函数实现。

```yaml
- test:
    name: $NodeName-同意-Approve
    setup:
        - ${sleep(1)}
    api: api_v1_Leave_Approve($AgreeID, $WorkItemId, $formId, $formNo, $ApproveType, $reason)
    teardown:
        - ${sleep(2)}
```
