### ISSUE TITLE
traceback: Keyerror

### ISSUE THREAD

**Issue by Kewings** [debugtalk/ApiTestEngine#48]
你好，
我使用python脚本调用ate部分，执行后报keyerror：
服务端返回值应该是如下：
```
{
  "statusString": "MUSS Request Successful",
  "id": "3ffd3ab1-6781-4fdd-808a-03fa48e7d5ec||f00c8366-fb7e-401f-9a33-8c7280f12044:f00c8366-fb7e-401f-9a33-8c7280f12044",
  "extension": [
    {
      "streamURL": "rtsp://159.99.251.223:554/5e551f88-d852-4106-9f57-d3377227d545_1_1.sdp||rtmps://159.99.251.223:790/live/5e551f88-d852-4106-9f57-d3377227d545_1_1_28b0efd8-4a6c-40f5-9dcf-f4c67146adaf",
      "name": "isomStreamResponseStatus"
    }
  ]
}
```

脚本报错：
```
Traceback (most recent call last):
  File "C:\Users\e567802\AppData\Local\Programs\Python\Python36\lib\site-packages\ate\utils.py", line 125, in query_json
    json_content = json_content[key]
KeyError: 'extension'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Projects\PythonProject\APITest.py", line 8, in <module>
    APITest.run(testcase_path)
  File "C:\Users\e567802\AppData\Local\Programs\Python\Python36\lib\site-packages\ate\runner.py", line 198, in run
    result = self._run_testset(testset, mapping)
  File "C:\Users\e567802\AppData\Local\Programs\Python\Python36\lib\site-packages\ate\runner.py", line 171, in _run_testset
    assert self._run_test(testcase)
  File "C:\Users\e567802\AppData\Local\Programs\Python\Python36\lib\site-packages\ate\runner.py", line 118, in _run_test
    extracted_variables_mapping = resp_obj.extract_response(extract_binds)
  File "C:\Users\e567802\AppData\Local\Programs\Python\Python36\lib\site-packages\ate\response.py", line 77, in extract_response
    extracted_variables_mapping[key] = self.extract_field(field)
  File "C:\Users\e567802\AppData\Local\Programs\Python\Python36\lib\site-packages\ate\response.py", line 51, in extract_field
    return utils.query_json(json_content, sub_query)
  File "C:\Users\e567802\AppData\Local\Programs\Python\Python36\lib\site-packages\ate\utils.py", line 130, in query_json
    raise exception.ParseResponseError("failed to query json when extracting response!")
ate.exception.ParseResponseError: failed to query json when extracting response!

```
我脚本中的调用：
```
from ate.runner import Runner
from ate import utils

if __name__ == '__main__' :
    #utils.SECRET_KEY='BaseTest'
    testcase_path='Test_Cases/Stream/'
    APITest=Runner()
    APITest.run(testcase_path)
```
请问是什么问题呢？

另外，询问下，我想改默认的debugtalk.py为BaseTest.py应该怎么设置？

谢谢。

**Comment by Kewings** [comment]
单步调试，每次都是到这里报错：
class BufferedIncrementalDecoder(IncrementalDecoder):
    """
    This subclass of IncrementalDecoder can be used as the baseclass for an
    incremental decoder if the decoder must be able to handle incomplete
    byte sequences.
    """
    def __init__(self, errors='strict'):
        IncrementalDecoder.__init__(self, errors)
        # undecoded input that is kept between calls to decode()
        self.buffer = b""

**Comment by Kewings** [comment]
应该是错在这里：
```
 testsets = testcase.load_testcases_by_path(path)
        for testset in testsets:
            try:
                result = self._run_testset(testset, mapping)
                assert result["success"]
                output.update(result["output"])
            except AssertionError:
                success = False

        return {
            "success": success,
            "output": output
        }
```

```
testset	dict: {'name': 'UMS_API_PostStreamConfig', 'config': {'path': 'C:\\\\Projects\\\\PythonProject\\\\Test_Cases/Stream/PostStreamConfig.yml', 'name': 'UMS_API_PostStreamConfig', 'variable_binds': OrderedDict([('sessionId', '${gen_guid()}'), ('token', '${Get_Token(sa,sa)}'), ('encryptionKey', '${gen_guid()}:${gen_guid()}'), ('envrId', '${gen_guid()}'), ('channelId', '${gen_random_number(4)}')]), 'request': {'verify': False, 'base_url': 'https://uspservices.api-ucp-platform.org/MUSS/ISOM/VideoMgmt/Media/Streams', 'headers': {'Authorization': 'basic MTM1MTIzNDU2Nzg6YQ==', 'ContentType': 'application/json', 'Accept': 'application/x-protobuf'}}}, 'api': {}, 'testcases': [{'name': 'PostStreamConfig_Valid', 'request': {'url': '/config', 'method': 'POST', 'json': {'identifiers': {'guid': '${join_with_symbol("||", $sessionId, $token, $encryptionKey)}'}, 'relation': {'id': '${join_with_symbol("||", $sessionId, $token, $encryptionKey)}', 'name': 'StreamRetrievedFromCamera', 'entityID': '${join_with_symbol...	
	'api' (2806047314808)	dict: {}	
	'config' (2806028006040)	dict: {'path': 'C:\\\\Projects\\\\PythonProject\\\\Test_Cases/Stream/PostStreamConfig.yml', 'name': 'UMS_API_PostStreamConfig', 'variable_binds': OrderedDict([('sessionId', '${gen_guid()}'), ('token', '${Get_Token(sa,sa)}'), ('encryptionKey', '${gen_guid()}:${gen_guid()}'), ('envrId', '${gen_guid()}'), ('channelId', '${gen_random_number(4)}')]), 'request': {'verify': False, 'base_url': 'https://uspservices.api-ucp-platform.org/MUSS/ISOM/VideoMgmt/Media/Streams', 'headers': {'Authorization': 'basic MTM1MTIzNDU2Nzg6YQ==', 'ContentType': 'application/json', 'Accept': 'application/x-protobuf'}}}	
		'name' (2806065811560)	str: UMS_API_PostStreamConfig	
		'path' (2806024760264)	str: C:\\Projects\\PythonProject\\Test_Cases/Stream/PostStreamConfig.yml	
		'request' (2806065815312)	dict: {'verify': False, 'base_url': 'https://uspservices.api-ucp-platform.org/MUSS/ISOM/VideoMgmt/Media/Streams', 'headers': {'Authorization': 'basic MTM1MTIzNDU2Nzg6YQ==', 'ContentType': 'application/json', 'Accept': 'application/x-protobuf'}}	
			'base_url' (2806065788976)	str: https://uspservices.api-ucp-platform.org/MUSS/ISOM/VideoMgmt/Media/Streams	
			'headers' (2806065902064)	dict: {'Authorization': 'basic MTM1MTIzNDU2Nzg6YQ==', 'ContentType': 'application/json', 'Accept': 'application/x-protobuf'}	
			'verify' (2806065815032)	bool: False	
			__len__	int: 3	
		'variable_binds' (2806065787632)	OrderedDict: OrderedDict([('sessionId', '${gen_guid()}'), ('token', '${Get_Token(sa,sa)}'), ('encryptionKey', '${gen_guid()}:${gen_guid()}'), ('envrId', '${gen_guid()}'), ('channelId', '${gen_random_number(4)}')])	
			'channelId' (2806065788784)	str: ${gen_random_number(4)}	
			'encryptionKey' (2806065788400)	str: ${gen_guid()}:${gen_guid()}	
			'envrId' (2806065814192)	str: ${gen_guid()}	
			'sessionId' (2806065787824)	str: ${gen_guid()}	
			'token' (2806065813128)	str: ${Get_Token(sa,sa)}	
			__len__	int: 5	
		__len__	int: 4	
	'name' (2806024760208)	str: UMS_API_PostStreamConfig	
	'testcases' (2806047247536)	<class 'list'>: [{'name': 'PostStreamConfig_Valid', 'request': {'url': '/config', 'method': 'POST', 'json': {'identifiers': {'guid': '${join_with_symbol("||", $sessionId, $token, $encryptionKey)}'}, 'relation': {'id': '${join_with_symbol("||", $sessionId, $token, $encryptionKey)}', 'name': 'StreamRetrievedFromCamera', 'entityID': '${join_with_symbol("_", $envrId, $channelId)}'}, 'protocol': 'RTSP/HTTP', 'retrievalType': 'Live'}}, 'validators': [{'check': 'content.extension.0.streamURL', 'comparator': 'len_gt', 'expected': 16}]}]	
		0	dict: {'name': 'PostStreamConfig_Valid', 'request': {'url': '/config', 'method': 'POST', 'json': {'identifiers': {'guid': '${join_with_symbol("||", $sessionId, $token, $encryptionKey)}'}, 'relation': {'id': '${join_with_symbol("||", $sessionId, $token, $encryptionKey)}', 'name': 'StreamRetrievedFromCamera', 'entityID': '${join_with_symbol("_", $envrId, $channelId)}'}, 'protocol': 'RTSP/HTTP', 'retrievalType': 'Live'}}, 'validators': [{'check': 'content.extension.0.streamURL', 'comparator': 'len_gt', 'expected': 16}]}	
			'name' (2806065904080)	str: PostStreamConfig_Valid	
			'request' (2806065904472)	dict: {'url': '/config', 'method': 'POST', 'json': {'identifiers': {'guid': '${join_with_symbol("||", $sessionId, $token, $encryptionKey)}'}, 'relation': {'id': '${join_with_symbol("||", $sessionId, $token, $encryptionKey)}', 'name': 'StreamRetrievedFromCamera', 'entityID': '${join_with_symbol("_", $envrId, $channelId)}'}, 'protocol': 'RTSP/HTTP', 'retrievalType': 'Live'}}	
				'json' (2806065983872)	dict: {'identifiers': {'guid': '${join_with_symbol("||", $sessionId, $token, $encryptionKey)}'}, 'relation': {'id': '${join_with_symbol("||", $sessionId, $token, $encryptionKey)}', 'name': 'StreamRetrievedFromCamera', 'entityID': '${join_with_symbol("_", $envrId, $channelId)}'}, 'protocol': 'RTSP/HTTP', 'retrievalType': 'Live'}	
					'identifiers' (2806065790064)	dict: {'guid': '${join_with_symbol("||", $sessionId, $token, $encryptionKey)}'}	
						'guid' (2806065984152)	str: ${join_with_symbol("||", $sessionId, $token, $encryptionKey)}	
						__len__	int: 1	
					'protocol' (2806065790896)	str: RTSP/HTTP	
					'relation' (2806065790576)	dict: {'id': '${join_with_symbol("||", $sessionId, $token, $encryptionKey)}', 'name': 'StreamRetrievedFromCamera', 'entityID': '${join_with_symbol("_", $envrId, $channelId)}'}	
						'entityID' (2806065790832)	str: ${join_with_symbol("_", $envrId, $channelId)}	
						'id' (2806065985384)	str: ${join_with_symbol("||", $sessionId, $token, $encryptionKey)}	
						'name' (2806065985272)	str: StreamRetrievedFromCamera	
						__len__	int: 3	
					'retrievalType' (2806066041136)	str: Live	
					__len__	int: 4	
				'method' (2806065904976)	str: POST	
				'url' (2806065905144)	str: /config	
				__len__	int: 3	
			'validators' (2806065790256)	<class 'list'>: [{'check': 'content.extension.0.streamURL', 'comparator': 'len_gt', 'expected': 16}]	
				0	dict: {'check': 'content.extension.0.streamURL', 'comparator': 'len_gt', 'expected': 16}	
				__len__	int: 1	
			__len__	int: 3	
		__len__	int: 1	
	__len__	int: 4	
```
mapping	dict: {}

**Comment by debugtalk** [comment]
@Kewings 可否将你的YAML格式测试用例贴出来看下？

**Comment by Kewings** [comment]
```
- config:
    name: UMS_API_PostStreamConfig
    import_module_items:
      - Test_Cases.Stream.debugtalk
    variable_binds: 
      - sessionId: ${gen_guid()}
      - token: ${Get_Token(sa,sa)}
      - encryptionKey: ${gen_guid()}:${gen_guid()}
      - envrId: ${gen_guid()}
      - channelId: ${gen_random_number(4)}     
    request: 
      verify: False
      base_url: https://uspservices.api-ucp-platform.org/MUSS/ISOM/VideoMgmt/Media/Streams
      headers: 
        Authorization: basic MTM1MTIzNDU2Nzg6YQ==
        ContentType: application/json
        Accept: application/x-protobuf
    

- test:
    name: PostStreamConfig_Valid
    request:
      url: /config
      method: POST
      json: 
        identifiers: 
          guid: ${join_with_symbol("||", $sessionId, $token, $encryptionKey)}
        relation: 
          id: ${join_with_symbol("||", $sessionId, $token, $encryptionKey)}
          name: StreamRetrievedFromCamera
          entityID: ${join_with_symbol("_", $envrId, $channelId)}
        protocol: RTSP/HTTP
        retrievalType: Live
#    extract_binds:
#      - response: content.extension
    validators:
#      - {"check": "content.StatusCode", "comparator": "eq", "expected": 0}
      - {"check": "content.extension.0.streamURL", "comparator": "len_gt", "expected": 16}
```

debugtalk.py
```
def join_with_symbol(connect_symbol, *args):
    content = connect_symbol.join(args).encode('utf8')
    return content        

def gen_random_number(max_no):
    random_number=random.randrange(1,max_no)
    return random_number

def gen_md5(*args):
    return hashlib.md5("".join(args).encode('utf-8')).hexdigest()

def gen_guid():
    return uuid.uuid4()
```
